package retrocesoenn;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.layout.Border;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ION Xtreme
 */
public class FromCliente extends javax.swing.JFrame {

    Sokets_Cliente cliente = new  Sokets_Cliente(this);
    Sokets_Server server =  new  Sokets_Server(this);
    JPanel jpanel = (JPanel) this.getContentPane();  
    int conteo=23;
    
    char [] caracteres;
    javax.swing.border.Border border = BorderFactory.createLineBorder(Color.black, 1); 
     
    /**
     * Creates new form FromCliente
     */
    public FromCliente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPuerto = new javax.swing.JTextField();
        btnConectar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        btnDesconectar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPuertoServer = new javax.swing.JTextField();
        cmdServer = new javax.swing.JToggleButton();
        txtMensajesRecibidos = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        cmdBorrar = new javax.swing.JButton();
        cmdDañada = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Paquete a enviar:");

        btnEnviar.setText("Enviar");
        btnEnviar.setEnabled(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jLabel2.setText("Puerto:");

        jLabel3.setText("Conexion");

        txtPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuertoActionPerformed(evt);
            }
        });

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        jLabel4.setText("IP:");

        txtIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPActionPerformed(evt);
            }
        });

        btnDesconectar.setText("Desconectar");
        btnDesconectar.setEnabled(false);
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });

        jLabel6.setText("Usuario:");

        jLabel7.setText("Servidor");

        jLabel8.setText("Puerto: ");

        txtPuertoServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuertoServerActionPerformed(evt);
            }
        });

        cmdServer.setText("Subir servidor");
        cmdServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdServerActionPerformed(evt);
            }
        });

        txtMensajesRecibidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensajesRecibidosActionPerformed(evt);
            }
        });

        jLabel5.setText("Tramas: ");

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });

        cmdDañada.setText("enviar trama bañada");
        cmdDañada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDañadaActionPerformed(evt);
            }
        });

        lbError.setBackground(new java.awt.Color(255, 0, 0));
        lbError.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(38, 38, 38)
                                .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDesconectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConectar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPuertoServer, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(cmdServer))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEnviar)
                                        .addGap(36, 36, 36)
                                        .addComponent(cmdDañada)
                                        .addGap(44, 44, 44)
                                        .addComponent(cmdBorrar))
                                    .addComponent(txtMensajesRecibidos, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 118, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPuertoServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdServer))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConectar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesconectar))
                .addGap(9, 9, 9)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMensajesRecibidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBorrar)
                    .addComponent(cmdDañada))
                .addGap(8, 8, 8)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
       this.cmdBorrarActionPerformed(evt);
         
        //recibe un array de string del longitud = a la cantidad de cpus q tenga la pc q contiene el consumo para cada cpu
        caracteres = this.txtMensajesRecibidos.getText().toCharArray();
        JTextField [] campos = new JTextField[caracteres.length];
        //creo un array de los jTextField del tamaño del array anterior
       int x=1;
       int x2=1;
       int x3=1;
       int y=352;
        for (int i = 0; i < caracteres.length; i++) {
            
            
            String aux = String.valueOf(caracteres[i]);
            campos[i]= new JTextField();
            campos[i].setText(aux);
            campos[i].setName(i+"");
            campos[i].setBackground(Color.WHITE);
            if(i<22){
                campos[i].setBounds(29*(x),y, 30, 30);
                x=x+1;
            }if (i>23&&i<46){
               
                y=390;
                campos[i].setBounds(29*(x2),y, 30, 30);
                 x2=x2+1;
            }if (i>47&&i<70){
               
                y=428;
                campos[i].setBounds(29*(x3),y, 30, 30);
                 x3=x3+1;
            }
            
            campos[i].setBorder(border);
            campos[i].setHorizontalAlignment(SwingConstants.CENTER);                
            
            jpanel.add(campos[i]);
            jpanel.repaint();
           
        }
        
        this.cmdBorrar.setEnabled(false);
        this.btnEnviar.setEnabled(false);
        this.cmdDañada.setEnabled(false);
        
        
        try {
            this.cliente.conectar();
        } catch (IOException ex) {
            Logger.getLogger(FromCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuertoActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
       
        try {
            this.cliente.conectar();
            this.txtIP.setEditable(false);
            this.txtPuerto.setEditable(false);
            this.btnConectar.setEnabled(false);
            this.btnDesconectar.setEnabled(true);
            this.txtMensajesRecibidos.setEditable(true);
            this.btnEnviar.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(FromCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnConectarActionPerformed

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
            this.txtIP.setEditable(true);
            this.txtPuerto.setEditable(true);
            this.btnConectar.setEnabled(true);
            this.btnDesconectar.setEnabled(false);
//            this.txtMensaje.setEditable(false);
            this.btnEnviar.setEnabled(false);
            this.jpanel.remove(1);
            this.jpanel.repaint();
                    
    }//GEN-LAST:event_btnDesconectarActionPerformed

    private void txtPuertoServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuertoServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuertoServerActionPerformed

    private void cmdServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdServerActionPerformed
        try {
            this.server.iniciarServidor(this.txtPuertoServer.getText());
        } catch (IOException ex) {
            Logger.getLogger(FromCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdServerActionPerformed

    private void txtMensajesRecibidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensajesRecibidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensajesRecibidosActionPerformed
public void limpiar(){
    System.out.println(this.jpanel.getComponentCount()+" -- Componentes1111");
    if(this.caracteres!=null){
        System.out.println(this.jpanel.getComponentCount()+" -- Componentes");
        System.out.println((23+this.caracteres.length)+" -- Caracteres");
        int max=this.jpanel.getComponentCount();
        for(int i = 23 ; i<max;i++){
            jpanel.remove(jpanel.getComponents()[23]);
            jpanel.repaint();
        }
        this.caracteres=null;
        }
    this.conteo=23;
}
public void limpiar2(int pos){
    int adicional=this.caracteres.length-pos;
    if(this.caracteres!=null){
        for(int i = (23+adicional) ; i<(this.caracteres.length+adicional);i++){
            jpanel.remove(jpanel.getComponents()[i]);
            jpanel.repaint();
        }
        this.caracteres=null;
        }
    this.conteo=23;
}
public void llenar(String mensaje){
    
    Hilopintar pintar = new  Hilopintar(this,mensaje,cliente);
    Thread hilo = new Thread (pintar);
    hilo.start();
}
public void pintar(String estado){
    
    if (estado.equals("true")){
    if(this.caracteres!=null){
            jpanel.getComponents()[conteo].setBackground(Color.green);
            jpanel.repaint();
            conteo++;
        }
    }else {
        
        if(this.caracteres!=null){
        
            jpanel.getComponents()[conteo].setBackground(Color.red);
            jpanel.repaint();
            conteo++;
        }
    } 
    
}
public void estados(){
        this.cmdBorrar.setEnabled(true);
        this.btnEnviar.setEnabled(true);
        this.cmdDañada.setEnabled(true);
}
    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdDañadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDañadaActionPerformed
        this.cmdBorrarActionPerformed(evt);
         
        //recibe un array de string del longitud = a la cantidad de cpus q tenga la pc q contiene el consumo para cada cpu
        caracteres = this.txtMensajesRecibidos.getText().toCharArray();
        JTextField [] campos = new JTextField[caracteres.length];
        //creo un array de los jTextField del tamaño del array anterior
       int x=1;
       int x2=1;
       int x3=1;
       int y=352;
        for (int i = 0; i < caracteres.length; i++) {
            
            
            String aux = String.valueOf(caracteres[i]);
            campos[i]= new JTextField();
            campos[i].setText(aux);
            campos[i].setName(i+"");
            campos[i].setBackground(Color.WHITE);
            if(i<22){
                campos[i].setBounds(29*(x),y, 30, 30);
                x=x+1;
            }if (i>23&&i<46){
               
                y=390;
                campos[i].setBounds(29*(x2),y, 30, 30);
                 x2=x2+1;
            }if (i>47&&i<70){
               
                y=428;
                campos[i].setBounds(29*(x3),y, 30, 30);
                 x3=x3+1;
            }
            
            campos[i].setBorder(border);
            campos[i].setHorizontalAlignment(SwingConstants.CENTER);                
            
            jpanel.add(campos[i]);
            jpanel.repaint();
           
        }
        this.cmdBorrar.setEnabled(false);
        this.btnEnviar.setEnabled(false);
        this.cmdDañada.setEnabled(false);
        
        try {
            this.cliente.conectarDañado();
        } catch (IOException ex) {
            Logger.getLogger(FromCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_cmdDañadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdDañada;
    private javax.swing.JToggleButton cmdServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel lbError;
    public javax.swing.JTextField txtIP;
    public javax.swing.JTextField txtMensajesRecibidos;
    public javax.swing.JTextField txtPuerto;
    public javax.swing.JTextField txtPuertoServer;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
